[build-system]
requires = ["setuptools", "wheel", "Cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "svcj_engine"
version = "1.0.0"
dependencies = ["numpy", "pandas"]
requires-python = ">=3.8"