[build-system]
requires = [
    "setuptools>=61.0",
    "wheel",
    "Cython>=3.0.0",
    "numpy<2.0.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "svcj_engine"
version = "1.0.0"
dependencies = [
    "numpy<2.0.0",
    "pandas>=1.3.0"
]
requires-python = ">=3.8"