[build-system]
requires = ["setuptools>=61.0", "wheel", "Cython>=0.29", "numpy>=1.21"]
build-backend = "setuptools.build_meta"

[project]
name = "svcj_engine"
version = "1.0.0"
dependencies = ["numpy", "pandas"]
requires-python = ">=3.8"